name: DefendVillage
version: 1.0.0
main: com.example.dv.DVPlugin
api-version: '1.21'
author: You
description: Defend the village from zombies!

commands:
  dv:
    description: Defend Village commands
    usage: /dv <help|create|delete|list|pos1|pos2|addvillager|addspawn|start|stop|join|leave|invite>
    permission: dv.use
    permission-message: "شما دسترسی به این دستور ندارید."

permissions:
  dv.use:
    default: true
  dv.admin:
    default: op
